package exceptionchaining;

import java.io.FileNotFoundException;
import java.io.IOException;

import javax.xml.bind.JAXBException;

public class TestException {

	public static void main(String[] args) {

		try {
			foo(); // винаги можеш да хванеш Exception или NullPointerException
			// дори когато не е в throws клаузата на метода
			// дори в throws клаузата на метода да е позочен
			// NullPointerException,
			// не е необходимо да се обработи в програмата
		} catch (IOException | JAXBException e) {
			e = new Exception();
			e.printStackTrace();
		} catch (Exception e) {
			e = new Exception();
			e.printStackTrace();
		}

	}

	public static void testException() throws FileNotFoundException, IOException {

	}

	public static void go() throws IOException, JAXBException, FileNotFoundException {

	}

	public static void bar() {

	}

	public static void foo() throws IOException, JAXBException {

	}

}
